spring.application.name=orders
server.port=8082
spring.h2.console.enabled=true
auth.service.url=http://localhost:8080/auth
products.service.url=http://localhost:8081/products
payments.service.url=http://localhost:8083/payments